name: "Nouvelles Solutions, Inc - AngularJS, iOS and Ruby on Rails"
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
exclude :  [ 'Gemfile' ,  'Gemfile.Lock' ]
paginate: 5
paginate_path: "blog/page/:num"
excerpt_separator: <!--more-->
sass :
  SYNTAX : sass     # SCSS | Sass
  Style : compact   # nested | expanded | Compact | compressed
